#!/usr/bin/env bash

# Overwrites
alias ls="ls --color"
alias cat="bat"
alias cd="z"

# Shortcuts
alias reloadbash="source ~/.bash_profile"
alias reloadzsh="source ~/.zshrc"
alias pls="sudo"
alias g="git"
alias rr="rm -rf"
alias zz="z -"
alias sshots="z ~/Pictures/screenshots"
alias dl="z ~/Downloads"
alias dt="z ~/Desktop"
alias p="z ~/projects"
alias g="git"

alias aliases="alias | sed 's/=.*//'"
alias functions="declare -f | grep '^[a-z].* ()' | sed 's/{$//'"
alias paths='echo -e ${PATH//:/\\n}'

alias l="ls -lahA $LS_COLORS $LS_TIMESTYLEISO $LS_GROUPDIRSFIRST"
alias ll="ls -lA $LS_COLORS"
alias lt="ls -lhAtr $LS_COLORS $LS_TIMESTYLEISO $LS_GROUPDIRSFIRST"
alias ld="ls -ld $LS_COLORS */"
alias lp="stat -c '%a %n' *"

unset LS_COLORS LS_TIMESTYLEISO LS_GROUPDIRSFIRST

alias ..="z .."
alias ...="z ../.."
alias ....="z ../../.."
alias .....="z ../../../.."
alias -- -="z -"                  # Go to previous dir with -
alias cd.='z $(readlink -f .)'    # Go to real dir (i.e. if current dir is linked)

# npm
alias ni="npm install"
alias nu="npm uninstall"
alias nup="npm update"
alias nri="rm -r node_modules && npm install"
alias ncd="npm-check -su"
alias nlg="npm list -g --depth=0"

# Network
alias ip="curl -s ipinfo.io | jq -r '.ip'"
alias ipl="ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'"
alias ifactive="ifconfig | pcregrep -M -o '^[^\t:]+:([^\n]|\n\t)*status: active'"

# Miscellaneous
alias hosts="sudo $EDITOR /etc/hosts"
alias quit="exit"
alias week="date +%V"
alias speedtest="wget -O /dev/null http://speed.transip.nl/100mb.bin"
alias grip="grip -b"
alias stfu="osascript -e 'set volume output muted true'"
alias pumpit="osascript -e 'set volume output volume 100'"

### DARWIN ONLY ###

# Copy pwd to clipboard
alias cpwd="pwd|tr -d '\n'|pbcopy"

# Exclude macOS specific files in ZIP archives
alias zip="zip -x *.DS_Store -x *__MACOSX* -x *.AppleDouble*"

# Flush DNS
alias flushdns="dscacheutil -flushcache && killall -HUP mDNSResponder"

# Start screen saver
alias afk="open /System/Library/CoreServices/ScreenSaverEngine.app"

# Log off
alias bye="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"

# Show/hide desktop icons
alias desktopshow="defaults write com.apple.finder CreateDesktop -bool true && killfinder"
alias desktophide="defaults write com.apple.finder CreateDesktop -bool false && killfinder"

# Recursively remove Apple meta files
alias cleanupds="find . -type f -name '*.DS_Store' -ls -delete"
alias cleanupad="find . -type d -name '.AppleD*' -ls -exec /bin/rm -r {} \;"

# Clean up LaunchServices to remove duplicates in the "Open With" menu
alias lscleanup="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user && killall Finder"

# Empty trash on mounted volumes and main HDD, and clear system logs
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl"

# Show system information
alias displays="system_profiler SPDisplaysDataType"
alias cpu="sysctl -n machdep.cpu.brand_string"
alias ram="top -l 1 -s 0 | grep PhysMem"
alias pbtext="pbpaste | textutil -convert txt -stdin -stdout -encoding 30 | pbcopy"
alias pbspaces="pbpaste | expand | pbcopy"

# Cleanup
alias findnmodules="find . -name 'node_modules' -type d -prune | xargs du -chs"
alias deletenmodules="find . -name 'node_modules' -type d -prune -exec rm -rf '{}' +"

alias finddists="find . -name '.dist' -type d -prune | xargs du -chs"
alias deletedists="find . -name '.dist' -type d -prune -exec rm -rf '{}' +"

alias findnnext="find . -name '.next' -type d -prune | xargs du -chs"
alias deletenext="find . -name '.next' -type d -prune -exec rm -rf '{}' +"

alias cleanupallinsalls="deletenmodules; deletedists; deletenext"
